name: 'yelpclimate'
version: '1.0.0'
profile: 'yelpclimate_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  yelpclimate:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: mart
